In [68]:
import pandas as pd
import numpy as np
import seaborn as sns

In [69]:
df=pd.read_csv("penguins.csv")
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    MALE  
1       3800.0  FEMALE  
2       3250.0  FEMALE  
3          NaN     NaN  
4       3450.0  FEMALE

In [70]:
df.shape

(344, 7)

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [72]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  10
dtype: int64

In [73]:
df.dropna(inplace=True)

In [74]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [75]:
df.sex.unique()

array(['MALE', 'FEMALE', '.'], dtype=object)

In [76]:
pd.get_dummies(df['sex']).head()

.  FEMALE  MALE
0  0       0     1
1  0       1     0
2  0       1     0
4  0       1     0
5  0       0     1

In [77]:
sex=pd.get_dummies(df['sex'],drop_first=True)
sex.head()

FEMALE  MALE
0       0     1
1       1     0
2       1     0
4       1     0
5       0     1

In [78]:
df.island.unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [79]:
pd.get_dummies(df['island']).head()

Biscoe  Dream  Torgersen
0       0      0          1
1       0      0          1
2       0      0          1
4       0      0          1
5       0      0          1

In [80]:
island=pd.get_dummies(df['island'],drop_first=True)
island.head(5)

Dream  Torgersen
0      0          1
1      0          1
2      0          1
4      0          1
5      0          1

In [81]:
new_data=pd.concat([df,island,sex],axis=1)
new_data.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  Dream  Torgersen  FEMALE  MALE  
0       3750.0    MALE      0          1       0     1  
1       3800.0  FEMALE      0          1       1     0  
2       3250.0  FEMALE      0          1       1     0  
4       3450.0  FEMALE      0          1       1     0  
5       3650.0    MALE      0          1       0     1

In [82]:
new_data.drop(['sex','island'],axis=1,inplace=True)
new_data.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0  Adelie            39.1           18.7              181.0       3750.0   
1  Adelie            39.5           17.4              186.0       3800.0   
2  Adelie            40.3           18.0              195.0       3250.0   
4  Adelie            36.7           19.3              193.0       3450.0   
5  Adelie            39.3           20.6              190.0       3650.0   

   Dream  Torgersen  FEMALE  MALE  
0      0          1       0     1  
1      0          1       1     0  
2      0          1       1     0  
4      0          1       1     0  
5      0          1       0     1

In [83]:
y=new_data.species
y.head()

0    Adelie
1    Adelie
2    Adelie
4    Adelie
5    Adelie
Name: species, dtype: object

In [84]:
y.unique()

array(['Adelie', 'Chinstrap', 'Gentoo'], dtype=object)

In [85]:
y=y.map({'Adelie':0,'Chinstrap':1,'Gentoo':2})
y.head()

0    0
1    0
2    0
4    0
5    0
Name: species, dtype: int64

In [86]:
new_data.drop('species',inplace=True,axis=1)
new_data.head()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  Dream  \
0            39.1           18.7              181.0       3750.0      0   
1            39.5           17.4              186.0       3800.0      0   
2            40.3           18.0              195.0       3250.0      0   
4            36.7           19.3              193.0       3450.0      0   
5            39.3           20.6              190.0       3650.0      0   

   Torgersen  FEMALE  MALE  
0          1       0     1  
1          1       1     0  
2          1       1     0  
4          1       1     0  
5          1       0     1

In [87]:
x=new_data

In [88]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [89]:
print('X_train: ',x_train.shape)
print('X_test: ',x_test.shape)
print('Y_train: ',y_train.shape)
print('Y_test: ',y_test.shape)

X_train:  (233, 8)
X_test:  (101, 8)
Y_train:  (233,)
Y_test:  (101,)


In [90]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=5,criterion='entropy',random_state=0)
classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=0)

In [91]:
y_pred=classifier.predict(x_test)
y_pred

array([1, 0, 0, 2, 1, 2, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0,
       2, 2, 2, 2, 2, 2, 0, 0, 1, 0, 1, 0, 2, 0, 0, 0, 2, 0, 1, 0, 2, 2,
       1, 2, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 0, 1, 0, 2, 2, 1, 2, 0, 2, 2,
       2, 0, 0, 2, 0, 0, 2, 0, 1, 2, 1, 0, 0], dtype=int64)

In [92]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,accuracy_score

In [93]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[50  0  0]
 [ 1 17  0]
 [ 0  0 33]]


In [94]:
accuracy_score(y_test,y_pred)

0.9900990099009901

In [95]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        50
           1       1.00      0.94      0.97        18
           2       1.00      1.00      1.00        33

    accuracy                           0.99       101
   macro avg       0.99      0.98      0.99       101
weighted avg       0.99      0.99      0.99       101

